language model for chat
MakarenkoAI/geometry-app pull request #9
Opened 2024-10-27 23:46 UTC by Avangard1917

2024-10-28 08:48 UTC, MakarenkoAI commented on requirements.txt
> +pandas
мне нужно было качать flask, flask_cors ещё

2024-10-28 08:51 UTC, MakarenkoAI requested changes

2024-10-28 08:51 UTC, MakarenkoAI commented on language_model/model/geometry_model.h5
для чего этот файл?

2024-10-28 08:51 UTC, MakarenkoAI commented on requirements.txt
> +pandas
flask, flask-cors

2024-10-28 16:49 UTC, Telyonok approved these changes

2024-10-29 09:56 UTC, MakarenkoAI approved these changes

2024-10-29 09:58 UTC, merged